summary: Path used to manage the list of products.
description: >-
  The REST endpoint/path used to list and create zero or more `Product` entities.  This path contains a
  `GET` and `POST` operation to perform the list and create tasks, respectively.
get:
  tags:
    - /products
  parameters:
    -
      examples:
        '{ "id": 3 }':
          value:
            id: 3
      name: ID
      description: ID
      schema: {}
      in: query
  responses:
    '200':
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Product'
          examples:
            product:
              value:
                id: 4
                name: kastan
                description: pruun
                price: 1
                userId: 3
      description: Successful response - returns an array of `Product` entities.
    '400':
      content:
        text/html:
          examples:
            Invalid authorization header:
              value: Invalid authorization header
      description: Bad request
    '401':
      content:
        text/html:
          examples:
            Missing authorization header:
              value: Missing authorization header
      description: Unauthorized
  security:
    -
      Bearer: []
  operationId: getProducts
  summary: List All Products
  description: Gets a list of all `Product` entities.
put:
  requestBody:
    description: Product to be edited
    content:
      application/json:
        examples:
          Product_edit:
            value:
              id: 6
              name: pirn
              description: punane
              price: 23
              userId: 6
    required: true
  tags:
    - /products
  responses:
    '200':
      description: Product edited
    '400':
      content:
        text/html:
          examples:
            ' Name, description and price are required':
              value: 'Name, description and price are required'
      description: 'Name, description and price are required'
    '401':
      content:
        text/html:
          examples:
            Invalid session:
              value: Invalid session
            Invalid authorization header:
              value: Invalid authorization header
      description: Unauthorized
    '404':
      content:
        text/html:
          examples:
            Product ID not found:
              value: Product ID not found
      description: Product ID not found
  security:
    -
      Bearer: []
  summary: A 'Product' to be edited
  description: A 'Product' to be edited
post:
  requestBody:
    description: '{name: "pirn", description: "puanae", price: 23}'
    content:
      application/json:
        examples:
          products_details:
            value:
              name: pirn
              description: punane
              price: 23
    required: true
  tags:
    - /products
  responses:
    '201':
      content:
        application/json: {}
      description: Succesful response - Product added
    '400':
      content:
        text/html:
          examples:
            'Name, description and price are required':
              value: 'Name, description and price are required'
      description: Name and price are required
    '401':
      content:
        text/html:
          examples:
            Invalid authorization header:
              value: Invalid authorization header
            Invalid session:
              value: Invalid session
      description: Unauthorized
  security:
    -
      Bearer: []
  operationId: addProduct
  summary: A new 'product' to be created
  description: A new 'product' is created
delete:
  requestBody:
    description: ID
    content:
      text/html:
        examples:
          ID:
            value:
              id: 3
    required: true
  responses:
    '204':
      description: Successful response - delets specific Product from array.
    '401':
      content:
        text/html:
          examples:
            Missing authorization header:
              value: Missing authorization header
      description: Unauthorized
    '404':
      description: Product ID not found in database.
  security:
    -
      Bearer: []
  summary: Deletes products from database
  description: Deletes products from database
